version: '3.8'
name: template03
services:
  product_service:
    image: product-mart-api
    build:
      context: ./product_service
      dockerfile: Dockerfile
    volumes:
      - ./product_service:/code/  # Sync local development directory with the container
    depends_on:
      - postgres_product_db
      - broker
    ports:
      - "8006:8000"  # Expose container port 8000 to host port 8000
  inventory_service:
    image: inventory-mart-api
    build:
      context: ./inventory_service
      dockerfile: Dockerfile
    volumes:
      - ./inventory_service:/code/  # Sync local development directory with the container
    depends_on:
      - postgres_inventory_db
      - broker
    ports:
      - "8007:8000"  # Expose container port 8000 to host port 8000

  postgres_product_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresContProduct
    environment:
      - POSTGRES_USER=ziakhan
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=Product_DB
    ports:
      - '5433:5432'
    volumes:
      - postgres_product_db:/var/lib/postgresql/data

  postgres_inventory_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresContInventory
    environment:
      - POSTGRES_USER=ziakhan
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=Inventory_DB
    ports:
      - '5434:5432'
    volumes:
      - postgres_inventory_db:/var/lib/postgresql/data

  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'Local Kafka Cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:19092'
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker

volumes:
  postgres_product_db:
    driver: local
  postgres_inventory_db:
    driver: local

networks:
  default:
    driver: bridge
